server:
  port: 8000

spring:
  application:
    name: cloud-consumer-feign-hystrix

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  hystrix:
    enabled: true
